const posts = [
    {
      id: 1,
      title: "Introduction to React",
      image: "https://via.placeholder.com/150/0000FF/808080?text=React",
      author: "John Doe",
      date: "2024-01-01",
      content: "Learn the basics of React, a popular JavaScript library for building user interfaces.",
    },
    {
      id: 2,
      title: "Advanced React Patterns",
      image: "https://via.placeholder.com/150/FF0000/FFFFFF?text=Advanced+React",
      author: "Jane Smith",
      date: "2024-02-15",
      content: "Explore advanced patterns and techniques in React development.",
    },
    {
      id: 3,
      title: "State Management with Redux",
      image: "https://via.placeholder.com/150/FFFF00/000000?text=Redux",
      author: "Alice Johnson",
      date: "2024-03-10",
      content: "A comprehensive guide to managing state in React applications using Redux.",
    },
    {
      id: 4,
      title: "React Router for Navigation",
      image: "https://via.placeholder.com/150/00FF00/000000?text=React+Router",
      author: "Bob Brown",
      date: "2024-04-05",
      content: "Learn how to use React Router for handling navigation in React applications.",
    },
    {
      id: 5,
      title: "Building Forms in React",
      image: "https://via.placeholder.com/150/FF00FF/FFFFFF?text=React+Forms",
      author: "Charlie Davis",
      date: "2024-05-20",
      content: "An in-depth look at building and validating forms in React.",
    },
    {
      id: 6,
      title: "Testing React Applications",
      image: "https://via.placeholder.com/150/00FFFF/000000?text=Testing+React",
      author: "Dana Evans",
      date: "2024-06-30",
      content: "Best practices for testing React applications with various tools and libraries.",
    },
  ];
  